biblioteca/urls.py
from django.urls import path
from . import views


app_name = "biblioteca"
urlpatterns = [
    path("index/", views.IndexView.as_view(), name="index"),

    path("", views.HomeView.as_view(), name="home"),
    path("cadastro/", views.CadastroView.as_view(), name="cadastro"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("cadastro_artigo/", views.Cadastro_artigoView.as_view(), name="cadastro_artigo"),
    path("minha_biblioteca/", views.ArtigoListView.as_view(), name="minha_biblioteca"),
]

login/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('cadastro/', views.cadastro, name='cadastro'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('novoArtigo/', views.novoArtigo, name='novoArtigo'),
    path('plataforma/', views.plataforma, name='plataforma'),
    path('profile_view/', views.profile_view, name='perfil'),
    path('favoritar/<int:artigo_id>/', views.favoritar_artigo, name='favoritar_artigo'),
    path('deletar_artigo/<int:artigo_id>/', views.deletar_artigo, name='deletar_artigo'),
    path('perfil/editar/', views.editar_perfil, name='editar_perfil'),
    path('perfil/deletar/', views.deletar_perfil, name='deletar_perfil'),
]

transcience/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from biblioteca import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path("biblioteca/", include ("biblioteca.urls")),
    path('auth/', include('login.urls')),
    path('', views.HomeView.as_view(), name='HomeView'), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

biblioteca/models.py
from django.db import models
from django.contrib.auth.models import User
# Tabelas primárias

class Ano(models.Model):
    descricao = models.CharField(max_length=255)

    def __str__(self):
        return self.descricao
    
class Relevancia(models.Model):
    descricao = models.TextField()
    imagem = models.ImageField(upload_to='biblioteca/images/relevancia/')

    def __str__(self):
        return self.descricao
    
class PalavraChave(models.Model):
    nome = models.CharField(max_length=100)

    def __str__(self):
        return self.nome

class Idioma(models.Model):
    descricao = models.CharField(max_length=100)

    def __str__(self):
        return self.descricao

class Autoria(models.Model):
    descricao = models.CharField(max_length=100)

    def __str__(self):
        return self.descricao

class Genero(models.Model):
    descricao = models.CharField(max_length=255)

    def __str__(self):
        return self.descricao
    
class Vinculo(models.Model):
    descricao = models.CharField(max_length=255)

    def __str__(self):
        return self.descricao

class Sexualidade(models.Model):
    nome = models.CharField(max_length=100)

    def __str__(self):
        return self.nome

# Tabelas secundária

class Usuarios(models.Model):
    nome = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    nascimento = models.DateField()
    senha = models.CharField(max_length=100)
    bio = models.CharField(max_length=100)
    data_registro = models.DateField()
    instituicao = models.CharField(max_length=100, default="Escola")
    foto = models.ImageField(upload_to='biblioteca/images/perfil/', default='biblioteca/images/perfil/foto_perfil.png')

    vinculo = models.ForeignKey(Vinculo, on_delete=models.CASCADE)
    genero = models.ForeignKey(Genero, on_delete=models.CASCADE)
    sexualidade = models.ForeignKey(Sexualidade, on_delete=models.CASCADE)


    def __str__(self):
        return self.nome

class Artigo(models.Model):
    titulo = models.CharField(max_length=200)
    link = models.CharField(max_length=255)
    autor = models.CharField(max_length=255)

    relevancia_id = models.ForeignKey(Relevancia, on_delete=models.CASCADE)
    ano_id = models.ForeignKey(Ano, on_delete=models.CASCADE)
    
    palavras_chave = models.ManyToManyField(PalavraChave, related_name='artigos')
    usuario = models.ManyToManyField(User, related_name='artigos')
    

    def novoArtigo(self, titulo=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self.novoArtigo(titulo, **extra_fields)


    def __str__(self):
        return self.titulo



class Favorito(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    artigo = models.ForeignKey(Artigo, on_delete=models.CASCADE)
    data_favorito = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.usuario} - {self.artigo}"

biblioteca/forms.py
# forms.py
from django import forms
from .models import Artigo

class ArtigoForm(forms.ModelForm):
    class Meta:
        model = Artigo
        fields = ['titulo', 'palavras_chave', 'link', 'ano_id', 'relevancia_id']
        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-input', 'placeholder': 'Título do artigo'}),
            'palavras_chave': forms.TextInput(attrs={'class': 'form-input', 'placeholder': 'Palavras-chave, separadas por vírgula'}),
            'link': forms.URLInput(attrs={'class': 'form-input', 'placeholder': 'Link do artigo'}),
            'ano_id': forms.NumberInput(attrs={'class': 'form-input', 'placeholder': 'Ano de publicação'}),
            'relevancia_id': forms.Select(attrs={'class': 'form-select'}),
        }
        labels = {
            'titulo': 'Título',
            'palavras_chave': 'Palavras-chave',
            'link': 'Link',
            'ano_id': 'Ano',
            'relevancia_id': 'Relevância',
        }

biblioteca/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views import generic
from .models import Artigo, Favorito
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q

class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = "biblioteca/index.html"
    context_object_name = "artigos"
    login_url = '/auth/login/' 
    

    def get_queryset(self):
        query = self.request.GET.get('q')  
        if query:
            return Artigo.objects.filter(
                Q(titulo__icontains=query) | 
                Q(autor__icontains=query) |  
                Q(palavras_chave__nome__icontains=query)).distinct()
        return Artigo.objects.all() 
    
    def get_context_data(self, **kwargs):
        usuario_atual = self.request.user
        context = super(IndexView, self).get_context_data(**kwargs)
        favoritos = Favorito.objects.filter(usuario=usuario_atual).values_list('artigo_id')
        favoritos_ids = []
        for f in favoritos:
            if (f[0] not in favoritos_ids):
                favoritos_ids.append(f[0])
        context['favoritos'] = favoritos_ids
        return context

class ArtigoListView(LoginRequiredMixin, generic.ListView):
    model = Artigo
    template_name = 'biblioteca/minha_biblioteca.html'
    context_object_name = 'artigos'

    def get_queryset(self):
        return Artigo.objects.filter(usuario=self.request.user)

        
   
    

def lista_artigos(request):
    usuario_atual = request.user

    if usuario_atual.is_authenticated:
        artigos = usuario_atual.artigos.all()  # Aqui usamos o related_name 'artigos'
    else:
        artigos = []

    return render(request, 'biblioteca/lista_artigos.html', {'artigos': artigos})

class HomeView(generic.ListView):
    template_name = "biblioteca/home.html"
    context_object_name = "biblioteca"

    def get_queryset(self):
        return Artigo.objects.all()

class CadastroView(generic.ListView):
    template_name = "biblioteca/cadastro.html"
    context_object_name = "biblioteca"

    def get_queryset(self):
        return Artigo.objects.all()
    
class LoginView(generic.ListView):
    template_name = "biblioteca/login.html"
    context_object_name = "biblioteca"

    def get_queryset(self):
        return Artigo.objects.all()
    
class Cadastro_artigoView(generic.ListView):
    template_name = "biblioteca/cadastro_artigo.html"
    context_object_name = "biblioteca"

    def get_queryset(self):
        return Artigo.objects.all()
    
class Minha_bibliotecaView(generic.ListView):
    template_name = "biblioteca/minha_biblioteca.html"
    context_object_name = "biblioteca"

    def get_queryset(self):
        return Artigo.objects.all()

def exemplo_view(request):
    if request.user.is_authenticated:
        usuario_logado = request.user  # Acessa o objeto User do usuário logado
        # Você pode acessar as informações do usuário, como:
        nome_usuario = usuario_logado.username
        email_usuario = usuario_logado.email
        # Ou qualquer outro campo associado ao modelo User

        # Exemplo de passar os dados para o template:
        return render(request, 'exemplo_template.html', {'usuario': usuario_logado})
    else:
        # Caso o usuário não esteja logado, você pode redirecioná-lo para a página de login
        return redirect('login')

biblioteca/templates/biblioteca/cadastro_artigo.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'fa/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'biblioteca/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;700&display=swap" rel="stylesheet">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
   
    <meta charset="UTF-8"/>
    <title>Transcience</title>
    <link rel="shortcut icon" type="imagex/png" href="{% static 'biblioteca/images/logo.png'%}">
      
</head>
<body id="body-pd">

<!-- Cabeçalho -->
<header class="header" id="header">
    <div class="header_toggle">
        <i class='bx bx-menu' id="header-toggle"></i>
    </div>
    <a>Submissão de artigos ao banco de dados</a>
</header>

<!-- Menu Lateral -->
<div class="l-navbar" id="nav-bar">
    <nav class="nav">
        <div>
            <a href="#" class="nav_logo">
                <img src="{% static 'biblioteca/images/logo.png' %}" alt="Logo" class="nav_logo-img">
                <span class="nav_logo-name">Transcience</span>
            </a>
            <div class="nav_list">
                <a href="{% url 'biblioteca:index' %}" class="nav_link active">
                    <i class='bx bx-grid-alt nav_icon'></i>
                    <span class="nav_name">Página inicial</span>
                </a>
                <a href="{% url 'perfil' %}" class="nav_link">
                    <i class='bx bx-user nav_icon'></i>
                    <span class="nav_name">Meu perfil</span>
                </a>
                <a href="{% url 'biblioteca:minha_biblioteca' %}" class="nav_link">
                    <i class='bx bx-message-square-detail nav_icon'></i>
                    <span class="nav_name">Biblioteca</span>
                </a>
                <a href="{% url 'novoArtigo' %}" class="nav_link">
                    <i class='bx bx-bookmark nav_icon'></i>
                    <span class="nav_name"> + Adicionar artigo</span>
                </a>
            </div>
        </div>
        <a href="#" class="nav_link">
            <i class='bx bx-log-out nav_icon'></i>
            <span class="nav_name">Sobre nós</span>
        </a>
    </nav>
</div>

{% if messages %}
    <div id="alert-box">
        {% for message in messages %}
            <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">
                {{ message }}
            </div>
        {% endfor %}
    </div>
{% endif %}

<div class="container mt-5">
    <form action="{% url 'novoArtigo' %}" method="POST">
        {% csrf_token %}
        <div class="row">
            
            <div class="col-md-6">
                
                <div class="form-group">
                    <label for="titulo">Título do Artigo</label>
                    <input type="text" name="titulo" id="titulo" class="form-control" placeholder="Digite o título" required>
                </div>

                

                

                <div class="form-group">
                    <label for="ano">Ano</label>
                    <select name="ano_id" id="ano" class="form-control" required>
                        <option selected disabled>Escolher...</option>
                        {% for ano in anos %}
                        <option value="{{ ano.id }}">{{ ano.descricao }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="link">Link do Artigo</label>
                    <input type="url" name="link" id="link" class="form-control" placeholder="Insira o link do artigo" required>
                </div>
            </div>

           
            <div class="col-md-6">
              


                <div class="form-group">
                    <label for="autor">Pesquisador(a)</label>
                    <input type="text" name="autor" id="autor" class="form-control" placeholder="Digite o nome do autor" required>
                </div>



                <fieldset class="form-group">
                    <legend>Palavras-chave</legend>
                    <div class="row">
                        <div class="col-sm-12">
                            {% for palavra in palavras_chave %}
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" name="palavras_chave" id="palavra{{ palavra.id }}" value="{{ palavra.id }}">
                                <label class="form-check-label" for="palavra{{ palavra.id }}">
                                    {{ palavra.nome }}
                                </label>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </fieldset>
                <div class="col-12 text-center mt-4">
                    <button type="submit" class="custom-button">Submeter</button>
                </div>
                
                
        </div>


        <div class="row mt-3">

        </div>
    </form>
</div>
<script>
    setTimeout(function() {
        let alertBox = document.getElementById("alert-box");
        if (alertBox) {
            alertBox.style.display = "none";
        }
    }, 3000);  // Esconde a mensagem após 3 segundos
</script>

</body>
</html>

biblioteca/templates/biblioteca/deletar_perfil.html
<h1>Tem certeza que deseja excluir seu perfil?</h1>
<p>Esta ação não pode ser desfeita.</p>

<form method="POST">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Confirmar Exclusão</button>
    <a href="{% url 'profile_view' %}" class="btn btn-secondary">Cancelar</a>
</form>

biblioteca/templates/biblioteca/minha_biblioteca.html
{% load static %}

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'fa/css/all.min.css' %}">
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'biblioteca/style.css' %}">
<link href="fontawesome/css/all.css" rel="stylesheet">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.7/css/all.css">
<head>
    <meta charset="UTF-8"/>
    <title>Transcience</title>
    <link rel="shortcut icon" type="imagex/png" href="{% static 'biblioteca/images/logo.png'%}">
</head>

<!--Menu no topo-->

<body id="body-pd">
  <header class="header" id="header">
      <div class="header_toggle"> <i class='bx bx-menu' id="header-toggle"></i> </div>

      
  
      {% if user.is_authenticated %}
      Biblioteca de {{ user.username }}!
 
      {% else %}
      <p>You are not logged in</p>
      <a href="{% url 'login' %}">Log In</a>
      {% endif %}
      


      <a>  </a>

      <form action="{% url 'logout' %}" method="post">
        {% csrf_token %}
        <button type="submit" class="logout-button">Sair</button>
      </form>
    <style>
    .artigo-item{
        width: 1100px;
        height: 160px;
    }

    .btn-container {
        display: flex;
        justify-content: center; 
        align-items: center; 
        gap: 10px; 
        margin-top: 100px; 
        margin-bottom: 40px;
    }

    .btn.btn-primary {
        background-color: #1F4172;
        color: white; 
        padding: 5px 15px; 
        border: none; 
        border-radius: 10px; 
        font-size: 18px; 
        box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1); 
        transition: background-color 0.3s ease, transform 0.3s ease; 
        display: inline-block;
        text-align: center;
        cursor: pointer;
    }
    
    .btn.btn-primary:hover {
        background-color: #357ABD;
        transform: translateY(-2px); 
    }
    
    .btn.btn-primary:active {
        transform: translateY(2px); 
        background-color: #134F8C; /* Cor de fundo mais escura para destacar */
        box-shadow: 0px 8px 12px rgba(0, 0, 0, 0.2); /* Sombra mais forte para destaque */
    }
    
    /* Efeito ao focar no botão */
    .btn.btn-primary:focus {
        outline: none; /* Remove a borda padrão */
        box-shadow: 0 0 20px rgba(31, 65, 114, 0.8); /* Sombra para indicar foco */
    }

    .btn.btn-secondary {
        background-color: #febbbb;
        color: white; 
        padding: 5px 15px; 
        border: none; 
        border-radius: 10px; 
        font-size: 18px; 
        box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1); 
        transition: background-color 0.3s ease, transform 0.3s ease; 
        display: inline-block;
        text-align: center;
        cursor: pointer;
    }
    
    .btn.btn-secondary:hover {
        background-color:rgb(236, 144, 144);
        transform: translateY(-2px); 
    }
    
    .btn.btn-secondary:active {
        transform: translateY(2px); 
        background-color: rgb(236, 144, 144); /* Cor de fundo mais escura para destacar */
        box-shadow: 0px 8px 12px rgba(0, 0, 0, 0.2); /* Sombra mais forte para destaque */
    }
    
    /* Efeito ao focar no botão */
    .btn.btn-secondary:focus {
        outline: none; /* Remove a borda padrão */
        box-shadow: 0 0 20px rgba(31, 65, 114, 0.8); /* Sombra para indicar foco */
    }
    
    h2 {
        font-family: 'Poppins', sans-serif; 
        font-weight: 600; 
        color: #1F4172; 
        font-size: 24px; 
        margin-bottom: 15px; 
        
        text-transform: uppercase; 
        margin-top: 30px;
    }
    
    
    </style>

  </header>


  <!--Menu lateral-->
  <div class="l-navbar" id="nav-bar">
    <nav class="nav">
        <div>
            <a href="#" class="nav_logo">
                <img src="{% static 'biblioteca/images/logo.png' %}" alt="Logo" class="nav_logo-img">
                <span class="nav_logo-name">Transcience</span>
            </a>
            <div class="nav_list">
                <a href="{% url 'biblioteca:index' %}" class="nav_link active">
                    <i class='bx bx-grid-alt nav_icon'></i>
                    <span class="nav_name">Página inicial</span>
                </a>
                <a href="{% url 'perfil' %}" class="nav_link">
                  <i class="fa-solid fa-circle-user"></i>
                    <span class="nav_name">Meu perfil</span>
                </a>
                <a href="{% url 'biblioteca:minha_biblioteca' %}" class="nav_link">
                    <i class='bx bx-message-square-detail nav_icon'></i>
                    <span class="nav_name">Biblioteca</span>
                </a>

                <a href="{% url 'novoArtigo' %}" class="nav_link">
                  <i class='bx bx-bookmark nav_icon'></i>
                  <span class="nav_name"> + Adicionar artigo</span>
                </a>
            </div>
        </div>
        <a href="#" class="nav_link">
            <i class='bx bx-log-out nav_icon'></i>
            <span class="nav_name">Sobre nós</span>
        </a>
    </nav>

    
</div>

<div class="btn-container">
    <button class="btn btn-primary" onclick="mostrarFavoritos()">Meus Favoritos</button>
    <button class="btn btn-secondary" onclick="mostrarSubmissoes()">Minhas Submissões</button>
</div>

<div class="content-container">
    <div class="content-container">
        <div id="favoritos" style="display: block;">
            
            <ul>
                {% for favorito in user.favorito_set.all %}
                    <li class="artigo-item" style="position: relative; padding-bottom: 30px;">
                        <a class="titulo-artigo" style="color: black;">
                            {{ favorito.artigo.titulo }}
                        </a>
    
                        <form action="{% url 'favoritar_artigo' favorito.artigo.id %}" method="post" class="favorite-form" id="favorite-form-{{ favorito.artigo.id }}">
                            {% csrf_token %}
                            <button type="submit" class="favorite-button" style="border: none; background: none; position: absolute; bottom: 5px; right: 5px;" id="favorite-btn-{{ favorito.artigo.id }}" onclick="toggleFavorite(event, {{ favorito.artigo.id }})">
                                <i class="fas fa-heart" id="heart-{{ favorito.artigo.id }}" style="font-size: 18px; color: red;"></i>
                            </button>
                        </form>
    
                        <p class="texto-menor" style="margin-top: 3px;">{{ favorito.artigo.autor }} <span style="margin-left: 5px;"></span> 
    
                        <div style="display: flex; align-items: center; margin-top: 10px;">
                            <a class="texto-menor">Palavras-chave:</a>
                            <div class="palavras-chave-container" style="margin-left: 5px;">
                                {% for palavra_chave in favorito.artigo.palavras_chave.all %}
                                    <span class="texto-menor" style="color: #1F4172;">{{ palavra_chave }}</span>
                                {% endfor %}
                            </div>
                        </div>
    
                        <p class="texto-menor" style="margin-top: 10px;">
                            <a href="{{ favorito.artigo.link }}" target="_blank">> Ler Mais</a>
                        </p>
                    </li>
                {% empty %}
                    <p>Você ainda não favoritou nenhum artigo.</p>
                {% endfor %}
            </ul>
        </div>
        

        <div id="submissoes" style="display: none;">
    
    
    {% block content %}
      
    
      {% if artigos %}
        <ul>
          {% for a in artigos %}
            <li class="artigo-item" style="position: relative; padding-bottom: 30px;">
                <a class="titulo-artigo" style="color: black;">
                    {{ a.titulo }}
                </a>
                <p class="texto-menor" style="margin-top: 3px;">Submetido por: {{ a.usuario.first.username }} <span style="margin-left: 5px;">({{ a.ano_id }})</span></p>
    
                <div style="display: flex; align-items: center; margin-top: 10px;">
                    <a class="texto-menor">Palavras-chave:</a>
                    <div class="palavras-chave-container" style="margin-left: 5px;">
                        {% for palavra_chave in a.palavras_chave.all %}
                            <span class="texto-menor" style="color: #1F4172;">{{ palavra_chave }}</span>
                        {% endfor %}
                    </div>
                </div>
    
                <p class="texto-menor" style="margin-top: 10px;">
                    <a href="{{ a.link }}" target="_blank">> Ler Mais</a>
                </p>
                <form action="{% url 'deletar_artigo' a.id %}" method="post" style="margin-left: 15px;">
                    {% csrf_token %}
                    <button type="submit" style="background: none; border: none; cursor: pointer;">
                        <i class="fas fa-trash-alt" style="color: red; border: none; background: none; position: absolute; bottom: 5px; right: 5px;"></i>
                    </button>
                </form>
            </li>
          {% endfor %}
        </ul>
      {% else %}
        <p>Você ainda não submeteu nenhum artigo.</p>
      {% endif %}
    {% endblock %}
    

    

<script>
    function mostrarFavoritos() {
        document.getElementById('favoritos').style.display = 'block';
        document.getElementById('submissoes').style.display = 'none';
    }
    
    function mostrarSubmissoes() {
        document.getElementById('favoritos').style.display = 'none';
        document.getElementById('submissoes').style.display = 'block';
    }
</script>